package com.netflix.mediaclient.service.logging.perf;
public enum Events {
    HOME_ACTIVITY_CREATED,
    NETFLIX_SERVICE_STARTED_COMMAND,
    LOLOMO_METADATA_FETCHED_EVENT,
    LOLOMO_MISMATCH_EVENT,
    DP_METADATA_FETCHED_EVENT,
    DP_PREFETCH_REQUEST_IN_FLIGHT_EVENT,
    APP_TRIM_MEMORY
}
